name: Node test unit

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: number

jobs:
  test-unit:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [14, 16, 18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        if: ${{ matrix.node-version >= inputs.node }}
      - uses: actions/setup-node@v3
        if: ${{ matrix.node-version >= inputs.node }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --ignore-scripts
        if: ${{ matrix.node-version >= inputs.node }}
      - run: npm run build
        if: ${{ matrix.node-version >= inputs.node }}
      - run: npm run test:unit
        if: ${{ matrix.node-version >= inputs.node }}
