name: Node E2E Tests

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npm run test:e2e
