name: Node test E2E

on:
  workflow_call:

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run test:e2e
