name: Node test unit

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: number

jobs:
  test-unit:
    if: matrix.node-version >= inputs.node
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run test:unit
