name: Node test unit

on:
  workflow_call:
    inputs:
      node:
        description: 'Node version (lowest LTS supported)'
        required: true
        type: number
        default: [14, 16, 18]

jobs:
  test-unit:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: ${{ inputs.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm run test:unit
