name: Node code analysis

on:
  workflow_call:

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: github/codeql-action/init@v1
        with:
          languages: typescript
      - uses: github/codeql-action/analyze@v1
